/**
 * Created by oxape on 2017/3/6.
 */
export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
export const INVALIDATE_SUBREDDIT  = 'INVALIDATE_SUBREDDIT'

export const REQUEST_SUBREDDIT = 'REQUEST_SUBREDDIT'
export const RECEIVE_SUBREDDIT = 'RECEIVE_SUBREDDIT'
